export const productCard = [
  {
    id: 1,
    category: "Vegetables",
    title: "Green Pepper",
    href: "/categories/vegetables",
    image: "/svg/fruit.svg",
    price: 20,
    badge: "red",
  },
  {
    id: 2,
    category: "Fruits",
    title: "Green Pepper",
    href: "/categories/fruits",
    image: "/svg/fruit.svg",
    price: 35,
    badge: "red",
  },
  {
    id: 3,
    category: "Seafood",
    title: "Green Pepper",
    href: "/categories/seafoods",
    image: "/svg/fruit.svg",
    price: 40,
    badge: "blue",
  },
  {
    id: 4,
    category: "Meat",
    title: "Green Pepper",
    href: "/categories/meat",
    image: "/svg/fruit.svg",
    price: 25,
    badge: "red",
  },
  {
    id: 5,
    category: "Milk",
    title: "Green Pepper",
    href: "/categories/dairy",
    image: "/svg/fruit.svg",
    price: 10,
    badge: "red",
  },
  {
    id: 6,
    category: "Cereals",
    title: "Green Pepper",
    href: "/categories/cereals",
    image: "/svg/fruit.svg",
    price: 24,
    badge: "red",
  },
];

export const categoryCard = [
  {
    id: 1,
    category: "Vegetables",
    title: "Vegetables",
    href: "/categories/vegetables",
    image: "/svg/vegetables.svg",
    price: 20,
    badge: "red",
  },
  {
    id: 2,
    category: "Fruits",
    title: "Fruits",
    href: "/categories/fruits",
    image: "/svg/fruit.svg",
    price: 35,
    badge: "red",
  },
  {
    id: 3,
    category: "Seafood",
    title: "Seafood",
    href: "/categories/seafoods",
    image: "/svg/shrimp.svg",
    price: 40,
    badge: "blue",
  },
  {
    id: 4,
    category: "Meat",
    title: "Meat",
    href: "/categories/meat",
    image: "/svg/meat.svg",
    price: 25,
    badge: "red",
  },
  {
    id: 5,
    category: "Dairy",
    title: "Dairy",
    href: "/categories/dairy",
    image: "/svg/milk.svg",
    price: 10,
    badge: "red",
  },
  {
    id: 6,
    category: "Cereals",
    title: "Cereals",
    href: "/categories/cereals",
    image: "/svg/cereals.svg",
    price: 24,
    badge: "red",
  },
];

// export const categoryCard = [
//   {
//     id: 1,
//     category: "Vegetable",
//     image: "/images/veg.png",
//   },
//   {
//     id: 2,
//     category: "Seafood",
//     image: "/images/veg.png",
//   },
//   {
//     id: 3,
//     category: "Eggs",
//     image: "/images/veg.png",
//   },
//   {
//     id: 4,
//     category: "Fresh Fruit",
//     image: "/images/veg.png",
//   },
//   {
//     id: 5,
//     category: "Fresh Milk",
//     image: "/images/veg.png",
//   },
//   {
//     id: 6,
//     category: "Meat",
//     image: "/images/veg.png",
//   },
//   {
//     id: 7,
//     category: "Drinks",
//     image: "/images/veg.png",
//   },
//   {
//     id: 8,
//     category: "Drinks",
//     image: "/images/veg.png",
//   },
//   {
//     id: 9,
//     category: "Drinks",
//     image: "/images/veg.png",
//   },
//   {
//     id: 10,
//     category: "Drinks",
//     image: "/images/veg.png",
//   },
//   {
//     id: 11,
//     category: "Drinks",
//     image: "/images/veg.png",
//   },
// ];
